### ISSUE TITLE
Linux keyboard arrows responsiveness

### ISSUE THREAD

**Issue by tYYGH** [octaspire/crates#5]
Hello, first _thank you_ for this great game!

I just wanted to report that some time-based levels (because of countdowns) are almost impossible to achieve due to a lack of responsiveness regarding keyboard arrows; for instance `PIKE`.
This is on Linux 6.6.8 (Archlinux), with a wired keyboard (“PS/2” DIN connector).

Do you need more information to locate/fix the issue?

**Comment by octaspire** [comment]
Hi!

Sorry that addressing this issue took some time! I have pushed a new branch **improve-player-input-handling** that has commit https://github.com/octaspire/crates/commit/b73797c5bf3cdcfd37c95aaaac04e314e8a6608b with a potential fix for the issue. It improves the input handling of the player entity on my tests. Can you confirm if the change fixes the issue for you too? After this commit, the player entity "remembers" the last input even if it is given before it has stopped moving. Before this change inputs given a bit "too early" were ignored. This caused the inputs to be finicky and slower to use.

**Comment by octaspire** [comment]
I will close this now.

**Comment by octaspire** [comment]
Fixed in version 0.7.4.
